services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio
    ports:
      - "5432:5432"
    volumes:
      - ./docker/desafio_test.sql:/docker-entrypoint-initdb.d/desafio_test.sql
